### ISSUE TITLE
Not compitible with prettyprinter-ansi-terminal 1.1

### ISSUE THREAD

**Issue by orivej** [pbogdan/nix-derivation-pretty#2]
I tried to rebuild this with the current nixpkgs. The compilation failed because `nix-derivation-pretty.cabal` specifies compatibility with `prettyprinter-ansi-terminal <1.2`, but `AnsiTerminal` was deleted in 1.1: https://github.com/quchen/prettyprinter/commit/1c85abd4a4aa9c8e11fce5e3981cc8560b568cee#diff-3071768bcf0edcdfc83926027507289b

**Comment by pbogdan** [comment]
Thank you for the report, latest master should now build with 1.0.x and 1.1.x. I will go ahead and close this now but please let me know if the issue persists or if you see any further problems.

**Comment by orivej** [comment]
Thank you!
